### ISSUE TITLE
Cvar to edit gangs max size.

### ISSUE THREAD

**Issue by Hexer10** [Headline22/Gangs#25]
I think that 15 gangs max size is not enoght, maybe a cvar to set the initial gang size and how much is increased after using a upgrade.

**Comment by Headline** [comment]
Done. 
hl_gangs_size_max_upgrades is the new cvar. It's default is nine. The old max was 15 because default gang size was 6 + 9 upgrades. By setting hl_gangs_size_max_upgrades, you can now upgrade past 15 to whatever you set it as'

https://github.com/Headline22/Gangs/commit/8b79408d77d0c8f477329a28503f8ceb568f3cb6
